// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TourPackages.Api.Data;

#nullable disable

namespace TourPackages.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610085846_AddPlacesAndAuthLinks")]
    partial class AddPlacesAndAuthLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TourPackages.Api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumberOfTravelers")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TourPackageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TourPackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TourPackages.Api.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A tropical paradise of palm-fringed beaches, emerald rice terraces, and clifftop temples. Bali blends laid-back surf towns with sacred mountain shrines, sunset cruises, and some of the warmest hospitality in Southeast Asia.",
                            Name = "Bali, Indonesia"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cradled between two alpine lakes beneath the Eiger, Mönch, and Jungfrau peaks, Interlaken is the gateway to the Swiss Alps. Ride scenic cogwheel railways, hike wildflower trails, and breathe in crisp mountain air.",
                            Name = "Interlaken, Switzerland"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Japan's ancient capital, where golden pavilions, vermilion torii gates, and tranquil bamboo groves sit beside traditional tea houses. Kyoto is the heart of Japanese culture across every season.",
                            Name = "Kyoto, Japan"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Whitewashed villages and blue-domed churches tumble down volcanic cliffs above the deep-blue Aegean. Santorini is famed for its caldera views, black-sand beaches, and unforgettable sunsets over Oia.",
                            Name = "Santorini, Greece"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Endless golden savannah and the stage for the Great Migration. The Serengeti offers close-up encounters with lions, elephants, and wildebeest herds on guided game drives across one of Africa's greatest wildernesses.",
                            Name = "Serengeti, Tanzania"
                        });
                });

            modelBuilder.Entity("TourPackages.Api.Models.PlaceImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("PlaceImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlaceId = 1,
                            SortOrder = 0,
                            Url = "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200"
                        },
                        new
                        {
                            Id = 2,
                            PlaceId = 1,
                            SortOrder = 1,
                            Url = "https://picsum.photos/seed/bali-2/1200/700"
                        },
                        new
                        {
                            Id = 3,
                            PlaceId = 1,
                            SortOrder = 2,
                            Url = "https://picsum.photos/seed/bali-3/1200/700"
                        },
                        new
                        {
                            Id = 4,
                            PlaceId = 1,
                            SortOrder = 3,
                            Url = "https://picsum.photos/seed/bali-4/1200/700"
                        },
                        new
                        {
                            Id = 5,
                            PlaceId = 1,
                            SortOrder = 4,
                            Url = "https://picsum.photos/seed/bali-5/1200/700"
                        },
                        new
                        {
                            Id = 6,
                            PlaceId = 2,
                            SortOrder = 0,
                            Url = "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200"
                        },
                        new
                        {
                            Id = 7,
                            PlaceId = 2,
                            SortOrder = 1,
                            Url = "https://picsum.photos/seed/alps-2/1200/700"
                        },
                        new
                        {
                            Id = 8,
                            PlaceId = 2,
                            SortOrder = 2,
                            Url = "https://picsum.photos/seed/alps-3/1200/700"
                        },
                        new
                        {
                            Id = 9,
                            PlaceId = 2,
                            SortOrder = 3,
                            Url = "https://picsum.photos/seed/alps-4/1200/700"
                        },
                        new
                        {
                            Id = 10,
                            PlaceId = 2,
                            SortOrder = 4,
                            Url = "https://picsum.photos/seed/alps-5/1200/700"
                        },
                        new
                        {
                            Id = 11,
                            PlaceId = 3,
                            SortOrder = 0,
                            Url = "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200"
                        },
                        new
                        {
                            Id = 12,
                            PlaceId = 3,
                            SortOrder = 1,
                            Url = "https://picsum.photos/seed/kyoto-2/1200/700"
                        },
                        new
                        {
                            Id = 13,
                            PlaceId = 3,
                            SortOrder = 2,
                            Url = "https://picsum.photos/seed/kyoto-3/1200/700"
                        },
                        new
                        {
                            Id = 14,
                            PlaceId = 3,
                            SortOrder = 3,
                            Url = "https://picsum.photos/seed/kyoto-4/1200/700"
                        },
                        new
                        {
                            Id = 15,
                            PlaceId = 3,
                            SortOrder = 4,
                            Url = "https://picsum.photos/seed/kyoto-5/1200/700"
                        },
                        new
                        {
                            Id = 16,
                            PlaceId = 4,
                            SortOrder = 0,
                            Url = "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1200"
                        },
                        new
                        {
                            Id = 17,
                            PlaceId = 4,
                            SortOrder = 1,
                            Url = "https://picsum.photos/seed/santorini-2/1200/700"
                        },
                        new
                        {
                            Id = 18,
                            PlaceId = 4,
                            SortOrder = 2,
                            Url = "https://picsum.photos/seed/santorini-3/1200/700"
                        },
                        new
                        {
                            Id = 19,
                            PlaceId = 4,
                            SortOrder = 3,
                            Url = "https://picsum.photos/seed/santorini-4/1200/700"
                        },
                        new
                        {
                            Id = 20,
                            PlaceId = 4,
                            SortOrder = 4,
                            Url = "https://picsum.photos/seed/santorini-5/1200/700"
                        },
                        new
                        {
                            Id = 21,
                            PlaceId = 5,
                            SortOrder = 0,
                            Url = "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200"
                        },
                        new
                        {
                            Id = 22,
                            PlaceId = 5,
                            SortOrder = 1,
                            Url = "https://picsum.photos/seed/serengeti-2/1200/700"
                        },
                        new
                        {
                            Id = 23,
                            PlaceId = 5,
                            SortOrder = 2,
                            Url = "https://picsum.photos/seed/serengeti-3/1200/700"
                        },
                        new
                        {
                            Id = 24,
                            PlaceId = 5,
                            SortOrder = 3,
                            Url = "https://picsum.photos/seed/serengeti-4/1200/700"
                        },
                        new
                        {
                            Id = 25,
                            PlaceId = 5,
                            SortOrder = 4,
                            Url = "https://picsum.photos/seed/serengeti-5/1200/700"
                        });
                });

            modelBuilder.Entity("TourPackages.Api.Models.TourPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("TourPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Seven days of pristine beaches, temples, and sunset cruises in tropical paradise.",
                            Destination = "Bali, Indonesia",
                            DurationDays = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
                            IsAvailable = true,
                            PlaceId = 1,
                            Price = 1299.00m,
                            Title = "Bali Beach Escape"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hike alpine trails, ride scenic railways, and breathe in the crisp mountain air.",
                            Destination = "Interlaken, Switzerland",
                            DurationDays = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800",
                            IsAvailable = true,
                            PlaceId = 2,
                            Price = 2199.00m,
                            Title = "Swiss Alps Adventure"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Explore ancient temples, bamboo groves, and traditional tea ceremonies.",
                            Destination = "Kyoto, Japan",
                            DurationDays = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800",
                            IsAvailable = true,
                            PlaceId = 3,
                            Price = 1750.00m,
                            Title = "Kyoto Cultural Journey"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Whitewashed villages, blue domes, and unforgettable Aegean sunsets.",
                            Destination = "Santorini, Greece",
                            DurationDays = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800",
                            IsAvailable = true,
                            PlaceId = 4,
                            Price = 1599.00m,
                            Title = "Santorini Island Getaway"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Witness the great migration up close on a guided wildlife safari.",
                            Destination = "Serengeti, Tanzania",
                            DurationDays = 8,
                            ImageUrl = "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800",
                            IsAvailable = true,
                            PlaceId = 5,
                            Price = 3299.00m,
                            Title = "Safari in the Serengeti"
                        });
                });

            modelBuilder.Entity("TourPackages.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TourPackages.Api.Models.Booking", b =>
                {
                    b.HasOne("TourPackages.Api.Models.TourPackage", "TourPackage")
                        .WithMany("Bookings")
                        .HasForeignKey("TourPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourPackages.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TourPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TourPackages.Api.Models.PlaceImage", b =>
                {
                    b.HasOne("TourPackages.Api.Models.Place", "Place")
                        .WithMany("Images")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("TourPackages.Api.Models.TourPackage", b =>
                {
                    b.HasOne("TourPackages.Api.Models.Place", "Place")
                        .WithMany("Packages")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Place");
                });

            modelBuilder.Entity("TourPackages.Api.Models.Place", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("TourPackages.Api.Models.TourPackage", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
